# filepath: c:\Users\singh\Documents\GitHub\PhishSnitch\config\config.yaml
gmail:
  credentials_path: config/credentials.json
  check_interval: 120  # 5 minutes in seconds

urlscan:
  api_key: "01979a1d-5f8e-7264-81a4-102222ca337d"
  cache_duration: 3600  # 1 hour in seconds

security:
  whitelist:
    # Common trusted email and business platforms
    - "gmail.com"
    - "google.com"
    - "microsoft.com"
    - "office365.com"
    - "outlook.com"
    - "linkedin.com"
    - "zoom.us"
    - "slack.com"
    - "github.com"
    - "amazonaws.com"
    - "dropbox.com"

  blacklist:
    # Known suspicious patterns (examples)
    - "secure-login-verify.com"
    - "account-security-check.com"
    - "banking-verify-now.com"
    
  risk_threshold: 10  # Alerts for threats scoring above this

alerts:
  history_path: data/alert_history.json
  desktop_notifications: true